const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");

dotenv.config();

const app = express();
const port = Number(process.env.PORT || 3000);
const groqApiKey = process.env.GROQ_API_KEY || "";
const groqModel = process.env.GROQ_MODEL || "openai/gpt-oss-20b";

app.use(cors());
app.use(express.json());

app.get("/health", (_req, res) => {
  res.json({ ok: true, service: "quiz-groq-backend" });
});

app.post("/api/ai-quiz", async (req, res) => {
  try {
    const topic = String(req.body.topic || "").trim();
    const difficulty = String(req.body.difficulty || "easy_to_medium").trim();
    const languageStyle = String(
      req.body.languageStyle || "simple",
    ).trim();
    const questionCount = Number(req.body.questionCount || 10);
    const questionType = String(req.body.questionType || "mcq").trim();

    if (!topic) {
      return res.status(400).json({ message: "Topic is required." });
    }

    if (!groqApiKey) {
      return res.status(500).json({
        message: "GROQ_API_KEY is missing in backend environment.",
      });
    }

    const prompt = [
      `Create ${questionCount} quiz questions for the subject: ${topic}.`,
      `Difficulty must be ${difficulty}.`,
      `Question type must be ${questionType}.`,
      `Language style must be ${languageStyle}.`,
      "All questions must be directly related to the requested topic.",
      "Do not repeat the same idea with different wording.",
      "Each question must have exactly 4 options.",
      "Only one option can be correct.",
      "Return only valid JSON using the provided schema.",
    ].join(" ");

    const groqResponse = await fetch(
      "https://api.groq.com/openai/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${groqApiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: groqModel,
          messages: [
            {
              role: "system",
              content:
                "You are a quiz generation engine. Produce high-quality, subject-specific multiple choice quiz questions. Return only structured JSON.",
            },
            {
              role: "user",
              content: prompt,
            },
          ],
          response_format: {
            type: "json_schema",
            json_schema: {
              name: "quiz_questions",
              strict: true,
              schema: {
                type: "object",
                properties: {
                  questions: {
                    type: "array",
                    minItems: questionCount,
                    maxItems: questionCount,
                    items: {
                      type: "object",
                      properties: {
                        title: { type: "string" },
                        question: { type: "string" },
                        options: {
                          type: "array",
                          minItems: 4,
                          maxItems: 4,
                          items: { type: "string" },
                        },
                        correctIndex: {
                          type: "integer",
                          minimum: 0,
                          maximum: 3,
                        },
                      },
                      required: [
                        "title",
                        "question",
                        "options",
                        "correctIndex",
                      ],
                      additionalProperties: false,
                    },
                  },
                },
                required: ["questions"],
                additionalProperties: false,
              },
            },
          },
        }),
      },
    );

    const result = await groqResponse.json();

    if (!groqResponse.ok) {
      const message =
        result?.error?.message || "Groq request failed while generating quiz.";
      return res.status(groqResponse.status).json({ message });
    }

    const content = result?.choices?.[0]?.message?.content;
    if (!content) {
      return res.status(500).json({
        message: "Groq returned an empty quiz response.",
      });
    }

    const parsed = JSON.parse(content);
    const questions = Array.isArray(parsed.questions) ? parsed.questions : [];

    if (questions.length === 0) {
      return res.status(500).json({
        message: "No questions were generated by Groq.",
      });
    }

    return res.json({
      topic,
      difficulty,
      languageStyle,
      questionType,
      questions: questions.map((item) => ({
        title: String(item.title || topic),
        question: String(item.question || ""),
        options: Array.isArray(item.options)
          ? item.options.map((option) => String(option))
          : [],
        correctIndex: Number(item.correctIndex || 0),
      })),
    });
  } catch (error) {
    return res.status(500).json({
      message:
        error instanceof Error ? error.message : "Unexpected backend error.",
    });
  }
});

app.listen(port, "0.0.0.0", () => {
  console.log(`Groq quiz backend running on port ${port}`);
});
